export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_START =  'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_END';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const INITIALIZE_HOMEPAGE_MOVIES = 'INITIALIZE_HOMEPAGE_MOVIES';